Bring in Neon changes to setcap due to build system cause FTBFS

diff --git a/debian/kinit.postinst.in b/debian/kinit.postinst.in
--- a/debian/kinit.postinst.in
+++ b/debian/kinit.postinst.in
@@ -1,19 +1,26 @@
 #!/bin/sh
 
 set -e
+    # Try to setcap or fall back to setuid.
+    # The specific setcap invocations also need to be whitelisted to make the
+    # build pass (in debian/meta/setcap.yaml as a nested array of argument
+    # arrays).
+    cap="CAP_SYS_RESOURCE=+ep"
+    path="/usr/lib/#MULTIARCH#/libexec/kf5/start_kdeinit"
+    if command -v setcap > /dev/null; then
+        if setcap $cap $path; then
+            echo "Setcap worked for $path!"
+        else
+            echo "Setcap failed for $path, falling back to setuid" >&2
+            chmod u+s $path
+        fi
+     else
+        echo "Setcap is not installed, falling back to setuid for $path" >&2
+        chmod u+s $path
 
-if [ "$1" = configure ]; then
-    # Set the capabilities
-    if command -v setcap > /dev/null && \
-       setcap "CAP_SYS_RESOURCE=+ep" \
-            "/usr/lib/#DEB_HOST_MULTIARCH#/libexec/kf5/start_kdeinit"; then
-        echo "Sucessfully set capabilities for start_kdeinit"
-    else
-        echo "Failed to set capabilities for start_kdeinit" >&2
     fi
 fi
 
 #DEBHELPER#
 
 exit 0
-
